# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

name: Build and Push Spring Boot App to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_ACCESS_PASSWORD }}" | docker login ghcr.io -u antbhavs --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t ghcr.io/antbhavs/degreeflowchart:latest .
          docker push ghcr.io/antbhavs/degreeflowchart:latest
